async function getTermsAndConditionsActualVersionInteractor(tncGateway) {
    return await tncGateway.getTermsAndConditionsActualVersion()
}

exports.getTermsAndConditionsActualVersionInteractor = getTermsAndConditionsActualVersionInteractor